// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
using Windows.System;

namespace Xaml.Behaviors.Uno.TestCompat;

/// <summary>
/// The Avalonia <c>PhysicalKey</c> values used by the shared tests (a QWERTY layout maps them to keys and characters).
/// </summary>
public enum PhysicalKey
{
    None,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Enter,
    Escape,
    Tab,
    Space,
    Backspace,
    Delete,
    Insert,
    Home,
    End,
    PageUp,
    PageDown,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ShiftLeft,
    ShiftRight,
    ControlLeft,
    ControlRight,
    AltLeft,
    AltRight,
    MetaLeft,
    MetaRight,
    CapsLock,
    ContextMenu,
    Minus,
    Equal,
    Comma,
    Period,
    Slash,
    Semicolon,
    Quote,
    BracketLeft,
    BracketRight,
    Backslash,
    Backquote,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    NumPad0,
    NumPad1,
    NumPad2,
    NumPad3,
    NumPad4,
    NumPad5,
    NumPad6,
    NumPad7,
    NumPad8,
    NumPad9,
}

/// <summary>
/// Maps <see cref="PhysicalKey"/> to WinUI keys and the characters they produce on a QWERTY layout.
/// </summary>
internal static class PhysicalKeyExtensions
{
    public static (VirtualKey Key, char? Character) ToVirtualKey(this PhysicalKey key, RawInputModifiers modifiers)
    {
        var shift = modifiers.HasFlag(RawInputModifiers.Shift);
        return key switch
        {
            PhysicalKey.Digit0 => (VirtualKey.Number0, '0'),
            PhysicalKey.Digit1 => (VirtualKey.Number1, '1'),
            PhysicalKey.Digit2 => (VirtualKey.Number2, '2'),
            PhysicalKey.Digit3 => (VirtualKey.Number3, '3'),
            PhysicalKey.Digit4 => (VirtualKey.Number4, '4'),
            PhysicalKey.Digit5 => (VirtualKey.Number5, '5'),
            PhysicalKey.Digit6 => (VirtualKey.Number6, '6'),
            PhysicalKey.Digit7 => (VirtualKey.Number7, '7'),
            PhysicalKey.Digit8 => (VirtualKey.Number8, '8'),
            PhysicalKey.Digit9 => (VirtualKey.Number9, '9'),
            PhysicalKey.KeyA => (VirtualKey.A, shift ? 'A' : 'a'),
            PhysicalKey.KeyB => (VirtualKey.B, shift ? 'B' : 'b'),
            PhysicalKey.KeyC => (VirtualKey.C, shift ? 'C' : 'c'),
            PhysicalKey.KeyD => (VirtualKey.D, shift ? 'D' : 'd'),
            PhysicalKey.KeyE => (VirtualKey.E, shift ? 'E' : 'e'),
            PhysicalKey.KeyF => (VirtualKey.F, shift ? 'F' : 'f'),
            PhysicalKey.KeyG => (VirtualKey.G, shift ? 'G' : 'g'),
            PhysicalKey.KeyH => (VirtualKey.H, shift ? 'H' : 'h'),
            PhysicalKey.KeyI => (VirtualKey.I, shift ? 'I' : 'i'),
            PhysicalKey.KeyJ => (VirtualKey.J, shift ? 'J' : 'j'),
            PhysicalKey.KeyK => (VirtualKey.K, shift ? 'K' : 'k'),
            PhysicalKey.KeyL => (VirtualKey.L, shift ? 'L' : 'l'),
            PhysicalKey.KeyM => (VirtualKey.M, shift ? 'M' : 'm'),
            PhysicalKey.KeyN => (VirtualKey.N, shift ? 'N' : 'n'),
            PhysicalKey.KeyO => (VirtualKey.O, shift ? 'O' : 'o'),
            PhysicalKey.KeyP => (VirtualKey.P, shift ? 'P' : 'p'),
            PhysicalKey.KeyQ => (VirtualKey.Q, shift ? 'Q' : 'q'),
            PhysicalKey.KeyR => (VirtualKey.R, shift ? 'R' : 'r'),
            PhysicalKey.KeyS => (VirtualKey.S, shift ? 'S' : 's'),
            PhysicalKey.KeyT => (VirtualKey.T, shift ? 'T' : 't'),
            PhysicalKey.KeyU => (VirtualKey.U, shift ? 'U' : 'u'),
            PhysicalKey.KeyV => (VirtualKey.V, shift ? 'V' : 'v'),
            PhysicalKey.KeyW => (VirtualKey.W, shift ? 'W' : 'w'),
            PhysicalKey.KeyX => (VirtualKey.X, shift ? 'X' : 'x'),
            PhysicalKey.KeyY => (VirtualKey.Y, shift ? 'Y' : 'y'),
            PhysicalKey.KeyZ => (VirtualKey.Z, shift ? 'Z' : 'z'),
            PhysicalKey.Enter => (VirtualKey.Enter, '\r'),
            PhysicalKey.Escape => (VirtualKey.Escape, null),
            PhysicalKey.Tab => (VirtualKey.Tab, '\t'),
            PhysicalKey.Space => (VirtualKey.Space, ' '),
            PhysicalKey.Backspace => (VirtualKey.Back, null),
            PhysicalKey.Delete => (VirtualKey.Delete, null),
            PhysicalKey.Insert => (VirtualKey.Insert, null),
            PhysicalKey.Home => (VirtualKey.Home, null),
            PhysicalKey.End => (VirtualKey.End, null),
            PhysicalKey.PageUp => (VirtualKey.PageUp, null),
            PhysicalKey.PageDown => (VirtualKey.PageDown, null),
            PhysicalKey.ArrowUp => (VirtualKey.Up, null),
            PhysicalKey.ArrowDown => (VirtualKey.Down, null),
            PhysicalKey.ArrowLeft => (VirtualKey.Left, null),
            PhysicalKey.ArrowRight => (VirtualKey.Right, null),
            PhysicalKey.ShiftLeft => (VirtualKey.LeftShift, null),
            PhysicalKey.ShiftRight => (VirtualKey.RightShift, null),
            PhysicalKey.ControlLeft => (VirtualKey.LeftControl, null),
            PhysicalKey.ControlRight => (VirtualKey.RightControl, null),
            PhysicalKey.AltLeft => (VirtualKey.LeftMenu, null),
            PhysicalKey.AltRight => (VirtualKey.RightMenu, null),
            PhysicalKey.MetaLeft => (VirtualKey.LeftWindows, null),
            PhysicalKey.MetaRight => (VirtualKey.RightWindows, null),
            PhysicalKey.CapsLock => (VirtualKey.CapitalLock, null),
            PhysicalKey.ContextMenu => (VirtualKey.Application, null),
            PhysicalKey.Minus => ((VirtualKey)189, shift ? '_' : '-'),
            PhysicalKey.Equal => ((VirtualKey)187, shift ? '+' : '='),
            PhysicalKey.Comma => ((VirtualKey)188, shift ? '<' : ','),
            PhysicalKey.Period => ((VirtualKey)190, shift ? '>' : '.'),
            PhysicalKey.Slash => ((VirtualKey)191, shift ? '?' : '/'),
            PhysicalKey.Semicolon => ((VirtualKey)186, shift ? ':' : ';'),
            PhysicalKey.Quote => ((VirtualKey)222, shift ? '"' : '\''),
            PhysicalKey.BracketLeft => ((VirtualKey)219, shift ? '{' : '['),
            PhysicalKey.BracketRight => ((VirtualKey)221, shift ? '}' : ']'),
            PhysicalKey.Backslash => ((VirtualKey)220, shift ? '|' : '\\'),
            PhysicalKey.Backquote => ((VirtualKey)192, shift ? '~' : '`'),
            PhysicalKey.F1 => (VirtualKey.F1, null),
            PhysicalKey.F2 => (VirtualKey.F2, null),
            PhysicalKey.F3 => (VirtualKey.F3, null),
            PhysicalKey.F4 => (VirtualKey.F4, null),
            PhysicalKey.F5 => (VirtualKey.F5, null),
            PhysicalKey.F6 => (VirtualKey.F6, null),
            PhysicalKey.F7 => (VirtualKey.F7, null),
            PhysicalKey.F8 => (VirtualKey.F8, null),
            PhysicalKey.F9 => (VirtualKey.F9, null),
            PhysicalKey.F10 => (VirtualKey.F10, null),
            PhysicalKey.F11 => (VirtualKey.F11, null),
            PhysicalKey.F12 => (VirtualKey.F12, null),
            PhysicalKey.NumPad0 => (VirtualKey.NumberPad0, '0'),
            PhysicalKey.NumPad1 => (VirtualKey.NumberPad1, '1'),
            PhysicalKey.NumPad2 => (VirtualKey.NumberPad2, '2'),
            PhysicalKey.NumPad3 => (VirtualKey.NumberPad3, '3'),
            PhysicalKey.NumPad4 => (VirtualKey.NumberPad4, '4'),
            PhysicalKey.NumPad5 => (VirtualKey.NumberPad5, '5'),
            PhysicalKey.NumPad6 => (VirtualKey.NumberPad6, '6'),
            PhysicalKey.NumPad7 => (VirtualKey.NumberPad7, '7'),
            PhysicalKey.NumPad8 => (VirtualKey.NumberPad8, '8'),
            PhysicalKey.NumPad9 => (VirtualKey.NumberPad9, '9'),
            _ => (VirtualKey.None, null),
        };
    }
}
