// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

namespace Xaml.PropertyGenerator
{
    /// <summary>
    /// Sources of the attributes consumed by the generator. They are emitted into every consuming compilation as
    /// internal, embedded (never visible across assemblies) and conditional (never persisted in metadata) types.
    /// </summary>
    internal static class AttributeSources
    {
        public const string Namespace = "Xaml.PropertyGenerator";
        public const string StyledPropertyAttributeName = Namespace + ".StyledPropertyAttribute";
        public const string DirectPropertyAttributeName = Namespace + ".DirectPropertyAttribute";
        public const string AttachedPropertyAttributeName = Namespace + ".AttachedPropertyAttribute";

        public const string Source = """
// <auto-generated/>
#nullable enable

namespace Xaml.PropertyGenerator
{
    /// <summary>
    /// Specifies the default binding mode of a generated property.
    /// </summary>
    /// <remarks>WinUI has no per-property default binding mode; the value is ignored on WinUI/Uno Platform.</remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    internal enum PropertyBindingMode
    {
        /// <summary>Uses the framework default (one way).</summary>
        Default = 0,
        /// <summary>One way binding.</summary>
        OneWay = 1,
        /// <summary>Two way binding.</summary>
        TwoWay = 2,
        /// <summary>One time binding.</summary>
        OneTime = 3,
        /// <summary>One way to source binding.</summary>
        OneWayToSource = 4,
    }

    /// <summary>
    /// Generates a value-store property for the annotated partial property: an Avalonia <c>StyledProperty</c> or a
    /// WinUI/Uno Platform <c>DependencyProperty</c>, plus the property accessors and the <c>{Name}Property</c> field.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.Conditional("XAML_PROPERTY_GENERATOR_ATTRIBUTES")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class StyledPropertyAttribute : global::System.Attribute
    {
        /// <summary>Gets or sets the constant default value.</summary>
        public object? DefaultValue { get; set; }

        /// <summary>Gets or sets a C# expression used as the default value when it is not a constant.</summary>
        public string? DefaultValueExpression { get; set; }

        /// <summary>Gets or sets the default binding mode (Avalonia only).</summary>
        public PropertyBindingMode DefaultBindingMode { get; set; }

        /// <summary>Gets or sets a value indicating whether the value is inherited (Avalonia only).</summary>
        public bool Inherits { get; set; }

        /// <summary>Gets or sets a value indicating whether the property is the XAML content property.</summary>
        public bool Content { get; set; }

        /// <summary>Gets or sets a value indicating whether XAML resolves element names assigned to the property (Avalonia only).</summary>
        public bool ResolveByName { get; set; }

        /// <summary>Gets or sets a value indicating whether XAML assigns bindings instead of applying them (Avalonia only).</summary>
        public bool AssignBinding { get; set; }
    }

    /// <summary>
    /// Generates a field-backed property for the annotated partial property: an Avalonia <c>DirectProperty</c> or a
    /// WinUI/Uno Platform <c>DependencyProperty</c> kept in sync with the backing field.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.Conditional("XAML_PROPERTY_GENERATOR_ATTRIBUTES")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class DirectPropertyAttribute : global::System.Attribute
    {
        /// <summary>Gets or sets the constant initial value.</summary>
        public object? DefaultValue { get; set; }

        /// <summary>Gets or sets a C# expression used as the initial value when it is not a constant.</summary>
        public string? DefaultValueExpression { get; set; }

        /// <summary>Gets or sets the default binding mode (Avalonia only).</summary>
        public PropertyBindingMode DefaultBindingMode { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the value is created on first access with its parameterless
        /// constructor (typically collections). Lazy properties are get-only.
        /// </summary>
        public bool Lazy { get; set; }

        /// <summary>Gets or sets a value indicating whether the property is the XAML content property.</summary>
        public bool Content { get; set; }
    }

    /// <summary>
    /// Generates an attached property with <c>Get{Name}</c>/<c>Set{Name}</c> accessors on the annotated class.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.Conditional("XAML_PROPERTY_GENERATOR_ATTRIBUTES")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class AttachedPropertyAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="AttachedPropertyAttribute"/> class.</summary>
        /// <param name="name">The property name.</param>
        /// <param name="valueType">The property value type.</param>
        public AttachedPropertyAttribute(string name, global::System.Type valueType)
        {
            Name = name;
            ValueType = valueType;
        }

        /// <summary>Gets the property name.</summary>
        public string Name { get; }

        /// <summary>Gets the property value type.</summary>
        public global::System.Type ValueType { get; }

        /// <summary>Gets or sets the type of the objects the property can be attached to.</summary>
        public global::System.Type? HostType { get; set; }

        /// <summary>Gets or sets the constant default value.</summary>
        public object? DefaultValue { get; set; }

        /// <summary>Gets or sets a C# expression used as the default value when it is not a constant.</summary>
        public string? DefaultValueExpression { get; set; }

        /// <summary>Gets or sets the default binding mode (Avalonia only).</summary>
        public PropertyBindingMode DefaultBindingMode { get; set; }

        /// <summary>Gets or sets a value indicating whether the value is inherited (Avalonia only).</summary>
        public bool Inherits { get; set; }

        /// <summary>Gets or sets a value indicating whether the value type is nullable (reference types).</summary>
        public bool IsNullable { get; set; }
    }
}
""";
    }
}
