// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Text;

namespace Xaml.PropertyGenerator
{
    /// <summary>Emits the generated source of one type.</summary>
    internal static class Emitter
    {
        private const string WinUIDependencyProperty = "global::Microsoft.UI.Xaml.DependencyProperty";
        private const string WinUIPropertyMetadata = "global::Microsoft.UI.Xaml.PropertyMetadata";

        /// <summary>The annotation of the property type parameter of WinUI/Uno Platform <c>DependencyProperty.Register</c>.</summary>
        private const string WinUIDynamicallyAccessedMembers =
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(" +
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | " +
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.NonPublicConstructors | " +
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields | " +
            "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties)";

        /// <summary>
        /// The suppression of IL2111 for registrations of property types with annotated members (for example
        /// <see cref="System.Type"/>, whose <c>TypeInitializer</c> getter requires the constructors of the instance).
        /// </summary>
        private const string WinUIAnnotatedMembersSuppression =
            "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2111\", Justification = " +
            "\"WinUI keeps the constructors, public fields and public properties of the property type for reflection based " +
            "bindings. Some of these members carry their own DynamicallyAccessedMembers requirements, which only matter to " +
            "binding paths that go through them; binding to the property value itself does not access them.\")]";

        private static readonly string[] s_avaloniaBindingModes =
        {
            "Default", "OneWay", "TwoWay", "OneTime", "OneWayToSource",
        };

        public static string Emit(TypeModel type)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n");
            sb.Append("#nullable enable\n");
            sb.Append("#pragma warning disable CS0108, CS0114, CS8600, CS8601, CS8603, CS8604, CS8618, CS9264\n");
            sb.Append(type.Usings);
            sb.Append('\n');

            if (type.Namespace.Length > 0)
            {
                sb.Append("namespace ").Append(type.Namespace).Append(";\n\n");
            }

            var depth = 0;
            for (var i = 0; i < type.ContainingTypes.Count; i++)
            {
                var declaration = type.ContainingTypes[i];
                if (i == type.ContainingTypes.Count - 1 && type.Platform == TargetPlatform.WinUI)
                {
                    foreach (var property in type.Properties)
                    {
                        if (property.Content)
                        {
                            Indent(sb, depth).Append("[global::Microsoft.UI.Xaml.Markup.ContentProperty(Name = \"").Append(property.Name).Append("\")]\n");
                        }
                    }
                }

                Indent(sb, depth).Append("partial ").Append(declaration.Keyword.Replace("static ", string.Empty))
                    .Append(' ').Append(declaration.Name).Append(TypeParameters(type, declaration, i)).Append('\n');
                Indent(sb, depth).Append("{\n");
                depth++;
            }

            var first = true;
            foreach (var property in type.Properties)
            {
                if (!first)
                {
                    sb.Append('\n');
                }

                first = false;

                if (type.Platform == TargetPlatform.WinUI)
                {
                    EmitWinUI(sb, depth, type, property);
                }
                else
                {
                    EmitAvalonia(sb, depth, type, property);
                }
            }

            while (depth > 0)
            {
                depth--;
                Indent(sb, depth).Append("}\n");
            }

            return sb.ToString();
        }

        /// <summary>
        /// The type parameter list of a containing type declaration. On WinUI, type parameters used as property types
        /// get the <c>[DynamicallyAccessedMembers]</c> annotation of the <c>DependencyProperty.Register</c> property type
        /// parameter (the attributes of partial type parameters are merged), so <c>typeof(T)</c> satisfies it (IL2087).
        /// </summary>
        private static string TypeParameters(TypeModel type, TypeDeclarationModel declaration, int level)
        {
            if (type.Platform != TargetPlatform.WinUI || !type.HasTrimmingAttributes || declaration.TypeParameters.Length == 0)
            {
                return declaration.TypeParameters;
            }

            var names = declaration.TypeParameters.Substring(1, declaration.TypeParameters.Length - 2).Split(',');
            var sb = new StringBuilder("<");
            for (var i = 0; i < names.Length; i++)
            {
                var name = names[i].Trim();
                if (i > 0)
                {
                    sb.Append(", ");
                }

                foreach (var property in type.Properties)
                {
                    if (property.Trimming.TypeParameterLevel == level && property.Trimming.TypeParameterName == name)
                    {
                        sb.Append('[').Append(WinUIDynamicallyAccessedMembers).Append("] ");
                        break;
                    }
                }

                sb.Append(name);
            }

            return sb.Append('>').ToString();
        }

        private static void EmitAvalonia(StringBuilder sb, int depth, TypeModel type, PropertyModel p)
        {
            var owner = type.OwnerType;
            var field = p.Name + "Property";

            FieldDoc(sb, depth, p, "avalonia");

            switch (p.Kind)
            {
                case PropertyKind.Styled:
                {
                    var register = new StringBuilder()
                        .Append("global::Avalonia.AvaloniaProperty.Register<").Append(owner).Append(", ").Append(p.Type).Append(">(nameof(").Append(p.Name).Append(')');
                    AppendAvaloniaOptions(register, p);
                    register.Append(')');

                    EmitAvaloniaField(sb, depth, p, "global::Avalonia.StyledProperty<" + p.Type + ">", register.ToString(), owner);

                    sb.Append('\n');
                    EmitAvaloniaAttributes(sb, depth, p);
                    Indent(sb, depth).Append(p.Modifiers).Append(' ').Append(p.Type).Append(' ').Append(p.Name).Append('\n');
                    Indent(sb, depth).Append("{\n");
                    Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get => GetValue(").Append(field).Append(");\n");
                    if (p.SetterModifiers is not null)
                    {
                        Indent(sb, depth + 1).Append(p.SetterModifiers).Append(p.SetterIsInit ? "init" : "set").Append(" => SetValue(").Append(field).Append(", value);\n");
                    }

                    Indent(sb, depth).Append("}\n");
                    break;
                }
                case PropertyKind.Direct:
                {
                    var register = new StringBuilder()
                        .Append("global::Avalonia.AvaloniaProperty.RegisterDirect<").Append(owner).Append(", ").Append(p.Type).Append(">(nameof(").Append(p.Name)
                        .Append("), static o => o.").Append(p.Name);
                    if (p.SetterModifiers is { Length: 0 } && !p.SetterIsInit)
                    {
                        register.Append(", static (o, v) => o.").Append(p.Name).Append(" = v");
                    }

                    if (p.DefaultBindingMode != 0)
                    {
                        register.Append(", defaultBindingMode: global::Avalonia.Data.BindingMode.").Append(s_avaloniaBindingModes[p.DefaultBindingMode]);
                    }

                    register.Append(')');

                    EmitAvaloniaField(sb, depth, p, "global::Avalonia.DirectProperty<" + owner + ", " + p.Type + ">", register.ToString(), owner);

                    sb.Append('\n');
                    EmitAvaloniaAttributes(sb, depth, p);
                    Indent(sb, depth).Append(p.Modifiers).Append(' ').Append(p.Type).Append(' ').Append(p.Name).Append('\n');
                    Indent(sb, depth).Append("{\n");
                    if (p.Lazy)
                    {
                        Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get => field ??= new ").Append(p.TypeOfType).Append("();\n");
                        Indent(sb, depth).Append("}\n");
                    }
                    else
                    {
                        Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get => field;\n");
                        if (p.SetterModifiers is not null)
                        {
                            Indent(sb, depth + 1).Append(p.SetterModifiers).Append(p.SetterIsInit ? "init" : "set").Append(" => SetAndRaise(").Append(field).Append(", ref field, value);\n");
                        }

                        Indent(sb, depth).Append('}');
                        if (p.DefaultValue is not null)
                        {
                            sb.Append(" = (").Append(p.Type).Append(")(").Append(p.DefaultValue).Append(");");
                        }

                        sb.Append('\n');
                    }

                    break;
                }
                case PropertyKind.Attached:
                {
                    var register = new StringBuilder()
                        .Append("global::Avalonia.AvaloniaProperty.RegisterAttached<").Append(owner).Append(", ").Append(p.HostType).Append(", ").Append(p.Type)
                        .Append(">(\"").Append(p.Name).Append('"');
                    AppendAvaloniaOptions(register, p);
                    register.Append(')');

                    EmitAvaloniaField(sb, depth, p, "global::Avalonia.AttachedProperty<" + p.Type + ">", register.ToString(), p.HostType);

                    sb.Append('\n');
                    AccessorDoc(sb, depth, "Gets", p.Name);
                    Indent(sb, depth).Append("public static ").Append(p.Type).Append(" Get").Append(p.Name).Append('(').Append(p.HostType).Append(" element) => element.GetValue(").Append(field).Append(");\n\n");
                    AccessorDoc(sb, depth, "Sets", p.Name);
                    Indent(sb, depth).Append("public static void Set").Append(p.Name).Append('(').Append(p.HostType).Append(" element, ").Append(p.Type).Append(" value) => element.SetValue(").Append(field).Append(", value);\n");
                    break;
                }
            }

            if (p.HasChangedHook)
            {
                sb.Append('\n');
                EmitHookDeclaration(sb, depth, p);
            }
        }

        private static void EmitAvaloniaField(StringBuilder sb, int depth, PropertyModel p, string fieldType, string registration, string handlerTarget)
        {
            var field = p.Name + "Property";
            if (!p.HasChangedHook)
            {
                Indent(sb, depth).Append(p.FieldAccessibility).Append(" static readonly ").Append(fieldType).Append(' ').Append(field).Append(" =\n");
                Indent(sb, depth + 1).Append(registration).Append(";\n");
                return;
            }

            Indent(sb, depth).Append(p.FieldAccessibility).Append(" static readonly ").Append(fieldType).Append(' ').Append(field).Append(" = Register").Append(field).Append("();\n\n");
            Indent(sb, depth).Append("private static ").Append(fieldType).Append(" Register").Append(field).Append("()\n");
            Indent(sb, depth).Append("{\n");
            Indent(sb, depth + 1).Append("var property = ").Append(registration).Append(";\n");
            Indent(sb, depth + 1).Append("global::Avalonia.AvaloniaObjectExtensions.AddClassHandler<").Append(handlerTarget).Append(", ").Append(p.Type)
                .Append(">(property.Changed, static (o, e) => ");
            if (p.Kind == PropertyKind.Attached)
            {
                sb.Append("On").Append(p.Name).Append("Changed(o, e.OldValue.GetValueOrDefault()!, e.NewValue.GetValueOrDefault()!));\n");
            }
            else
            {
                sb.Append("o.On").Append(p.Name).Append("Changed(e.OldValue.GetValueOrDefault()!, e.NewValue.GetValueOrDefault()!));\n");
            }

            Indent(sb, depth + 1).Append("return property;\n");
            Indent(sb, depth).Append("}\n");
        }

        private static void AppendAvaloniaOptions(StringBuilder register, PropertyModel p)
        {
            if (p.DefaultValue is not null)
            {
                register.Append(", defaultValue: (").Append(p.Type).Append(")(").Append(p.DefaultValue).Append(')');
            }

            if (p.Inherits)
            {
                register.Append(", inherits: true");
            }

            if (p.DefaultBindingMode != 0)
            {
                register.Append(", defaultBindingMode: global::Avalonia.Data.BindingMode.").Append(s_avaloniaBindingModes[p.DefaultBindingMode]);
            }
        }

        private static void EmitAvaloniaAttributes(StringBuilder sb, int depth, PropertyModel p)
        {
            if (p.Content)
            {
                Indent(sb, depth).Append("[global::Avalonia.Metadata.Content]\n");
            }

            if (p.ResolveByName)
            {
                Indent(sb, depth).Append("[global::Avalonia.Controls.ResolveByName]\n");
            }

            if (p.AssignBinding)
            {
                Indent(sb, depth).Append("[global::Avalonia.Data.AssignBinding]\n");
            }
        }

        /// <summary>
        /// The property type a WinUI dependency property is registered with.
        /// </summary>
        /// <remarks>
        /// Native WinUI resolves the property types of a class through the XAML type information of the application,
        /// which fails for managed enums and for the <c>DependencyProperty</c> and <c>System.Type</c> types: those
        /// properties are registered as <c>object</c> there (XAML still converts strings with the property type).
        /// </remarks>
        private static string RegisteredType(TypeModel type, PropertyModel p)
            => p.IsEnum && type.IsNativeWinUI ? "object" : p.TypeOfType;

        private static void EmitWinUI(StringBuilder sb, int depth, TypeModel type, PropertyModel p)
        {
            var owner = type.OwnerType;
            var field = p.Name + "Property";
            var defaultValue = p.DefaultValue is null
                ? "default(" + p.Type + ")"
                : "(" + p.Type + ")(" + p.DefaultValue + ")";
            if (p.Lazy)
            {
                defaultValue = "null";
            }

            var callback = BuildWinUICallback(type, p);

            FieldDoc(sb, depth, p, "dependency");
            Indent(sb, depth).Append(p.FieldAccessibility).Append(" static readonly ").Append(WinUIDependencyProperty).Append(' ').Append(field);
            if (p.Trimming.HasAnnotatedMembers && type.HasTrimmingAttributes)
            {
                // The registration runs in a helper method that can carry the suppression (field initializers cannot).
                sb.Append(" = Register").Append(field).Append("();\n\n");
                Indent(sb, depth).Append(WinUIAnnotatedMembersSuppression).Append('\n');
                Indent(sb, depth).Append("private static ").Append(WinUIDependencyProperty).Append(" Register").Append(field).Append("() =>\n");
            }
            else
            {
                sb.Append(" =\n");
            }

            Indent(sb, depth + 1).Append(WinUIDependencyProperty).Append(p.Kind == PropertyKind.Attached ? ".RegisterAttached(\"" + p.Name + "\"" : ".Register(nameof(" + p.Name + ")")
                .Append(", typeof(").Append(RegisteredType(type, p)).Append("), typeof(").Append(owner).Append("), new ").Append(WinUIPropertyMetadata).Append('(').Append(defaultValue);
            if (callback is not null)
            {
                sb.Append(", ").Append(callback);
            }

            sb.Append("));\n\n");

            switch (p.Kind)
            {
                case PropertyKind.Styled:
                    Indent(sb, depth).Append(p.Modifiers).Append(' ').Append(p.Type).Append(' ').Append(p.Name).Append('\n');
                    Indent(sb, depth).Append("{\n");
                    Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get => (").Append(p.Type).Append(")GetValue(").Append(field).Append(")!;\n");
                    if (p.SetterModifiers is not null)
                    {
                        Indent(sb, depth + 1).Append(p.SetterModifiers).Append(p.SetterIsInit ? "init" : "set").Append(" => SetValue(").Append(field).Append(", value);\n");
                    }

                    Indent(sb, depth).Append("}\n");
                    break;
                case PropertyKind.Direct when p.Lazy:
                    Indent(sb, depth).Append(p.Modifiers).Append(' ').Append(p.Type).Append(' ').Append(p.Name).Append('\n');
                    Indent(sb, depth).Append("{\n");
                    Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get\n");
                    Indent(sb, depth + 1).Append("{\n");
                    Indent(sb, depth + 2).Append("if (GetValue(").Append(field).Append(") is not ").Append(p.TypeOfType).Append(" value)\n");
                    Indent(sb, depth + 2).Append("{\n");
                    Indent(sb, depth + 3).Append("value = new ").Append(p.TypeOfType).Append("();\n");
                    Indent(sb, depth + 3).Append("SetValue(").Append(field).Append(", value);\n");
                    Indent(sb, depth + 2).Append("}\n\n");
                    Indent(sb, depth + 2).Append("return value;\n");
                    Indent(sb, depth + 1).Append("}\n");
                    Indent(sb, depth).Append("}\n");
                    break;
                case PropertyKind.Direct:
                    Indent(sb, depth).Append(p.Modifiers).Append(' ').Append(p.Type).Append(' ').Append(p.Name).Append('\n');
                    Indent(sb, depth).Append("{\n");
                    Indent(sb, depth + 1).Append(p.GetterModifiers).Append("get => field;\n");
                    if (p.SetterModifiers is not null)
                    {
                        Indent(sb, depth + 1).Append(p.SetterModifiers).Append(p.SetterIsInit ? "init" : "set").Append('\n');
                        Indent(sb, depth + 1).Append("{\n");
                        Indent(sb, depth + 2).Append("if (global::System.Collections.Generic.EqualityComparer<").Append(p.Type).Append(">.Default.Equals(field, value))\n");
                        Indent(sb, depth + 2).Append("{\n");
                        Indent(sb, depth + 3).Append("return;\n");
                        Indent(sb, depth + 2).Append("}\n\n");
                        Indent(sb, depth + 2).Append("field = value;\n");
                        Indent(sb, depth + 2).Append("SetValue(").Append(field).Append(", value);\n");
                        Indent(sb, depth + 1).Append("}\n");
                    }

                    Indent(sb, depth).Append('}');
                    if (p.DefaultValue is not null)
                    {
                        sb.Append(" = (").Append(p.Type).Append(")(").Append(p.DefaultValue).Append(");");
                    }

                    sb.Append('\n');
                    break;
                case PropertyKind.Attached:
                    AccessorDoc(sb, depth, "Gets", p.Name);
                    Indent(sb, depth).Append("public static ").Append(p.Type).Append(" Get").Append(p.Name).Append('(').Append(p.HostType).Append(" element) => (")
                        .Append(p.Type).Append(")element.GetValue(").Append(field).Append(")!;\n\n");
                    AccessorDoc(sb, depth, "Sets", p.Name);
                    Indent(sb, depth).Append("public static void Set").Append(p.Name).Append('(').Append(p.HostType).Append(" element, ").Append(p.Type)
                        .Append(" value) => element.SetValue(").Append(field).Append(", value);\n");
                    break;
            }

            if (p.HasChangedHook)
            {
                sb.Append('\n');
                EmitHookDeclaration(sb, depth, p);
            }
        }

        private static string? BuildWinUICallback(TypeModel type, PropertyModel p)
        {
            var owner = type.OwnerType;
            var syncDirect = p.Kind == PropertyKind.Direct && !p.Lazy && p.SetterModifiers is not null;
            var routeChanged = type.ChangedMethod is not null && p.Kind != PropertyKind.Attached;
            if (!syncDirect && !routeChanged && !p.HasChangedHook)
            {
                return null;
            }

            var sb = new StringBuilder("static (d, e) =>\n        {\n");
            if (p.Kind == PropertyKind.Attached)
            {
                sb.Append("            On").Append(p.Name).Append("Changed((").Append(p.HostType).Append(")d, (").Append(p.Type).Append(")e.OldValue!, (").Append(p.Type).Append(")e.NewValue!);\n");
            }
            else
            {
                sb.Append("            var owner = (").Append(owner).Append(")d;\n");
                if (syncDirect)
                {
                    sb.Append("            owner.").Append(p.Name).Append(" = (").Append(p.Type).Append(")e.NewValue!;\n");
                }

                if (p.HasChangedHook)
                {
                    sb.Append("            owner.On").Append(p.Name).Append("Changed((").Append(p.Type).Append(")e.OldValue!, (").Append(p.Type).Append(")e.NewValue!);\n");
                }

                if (routeChanged)
                {
                    sb.Append("            owner.").Append(type.ChangedMethod).Append("(e);\n");
                }
            }

            sb.Append("        }");
            return sb.ToString();
        }

        private static void EmitHookDeclaration(StringBuilder sb, int depth, PropertyModel p)
        {
            Indent(sb, depth).Append("/// <summary>Called after the value of <see cref=\"").Append(p.Kind == PropertyKind.Attached ? p.Name + "Property" : p.Name).Append("\"/> changed.</summary>\n");
            if (p.Kind == PropertyKind.Attached)
            {
                Indent(sb, depth).Append("static partial void On").Append(p.Name).Append("Changed(").Append(p.HostType).Append(" element, ").Append(p.Type).Append(" oldValue, ").Append(p.Type).Append(" newValue);\n");
            }
            else
            {
                Indent(sb, depth).Append("partial void On").Append(p.Name).Append("Changed(").Append(p.Type).Append(" oldValue, ").Append(p.Type).Append(" newValue);\n");
            }
        }

        private static void FieldDoc(StringBuilder sb, int depth, PropertyModel p, string kind)
        {
            Indent(sb, depth).Append("/// <summary>\n");
            if (p.Kind == PropertyKind.Attached)
            {
                Indent(sb, depth).Append("/// Identifies the ").Append(p.Name).Append(" attached ").Append(kind).Append(" property.\n");
            }
            else
            {
                Indent(sb, depth).Append("/// Identifies the <seealso cref=\"").Append(p.Name).Append("\"/> ").Append(kind).Append(" property.\n");
            }

            Indent(sb, depth).Append("/// </summary>\n");
        }

        private static void AccessorDoc(StringBuilder sb, int depth, string verb, string name)
        {
            Indent(sb, depth).Append("/// <summary>").Append(verb).Append(" the value of the ").Append(name).Append(" attached property.</summary>\n");
            Indent(sb, depth).Append("/// <param name=\"element\">The element.</param>\n");
            if (verb == "Sets")
            {
                Indent(sb, depth).Append("/// <param name=\"value\">The value.</param>\n");
            }
            else
            {
                Indent(sb, depth).Append("/// <returns>The value.</returns>\n");
            }
        }

        private static StringBuilder Indent(StringBuilder sb, int depth) => sb.Append(' ', depth * 4);
    }
}
