// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Xaml.Behaviors.SourceGenerators
{
    public partial class XamlBehaviorsGenerator
    {
        private record TriggerParameter(string Name, string Type, RefKind RefKind);

        private record TriggerInfo(
            string? Namespace,
            string ClassName,
            string Accessibility,
            string TargetTypeName,
            string EventName,
            string EventHandlerType,
            ImmutableArray<TriggerParameter> Parameters,
            Diagnostic? Diagnostic = null);

        private void RegisterTriggerGeneration(IncrementalGeneratorInitializationContext context)
        {
            var triggers = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateTypedTriggerAttributeName,
                    predicate: static (_, _) => true,
                    transform: (ctx, _) => GetTriggerToGenerate(ctx))
                .SelectMany((x, _) => x);

            var assemblyTriggers = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsAssemblyAttribute(node),
                    transform: (ctx, _) => GetAssemblyTriggerFromAttributeSyntax(ctx))
                .SelectMany((info, _) => info);

            var uniqueTriggers = triggers
                .Collect()
                .Combine(assemblyTriggers.Collect())
                .SelectMany((data, _) => EnsureUniqueTriggers(data.Left.Concat(data.Right)));

            context.RegisterSourceOutput(uniqueTriggers, ExecuteGenerateTrigger);
        }

        private ImmutableArray<TriggerInfo> GetTriggerToGenerate(GeneratorAttributeSyntaxContext context)
        {
            var results = ImmutableArray.CreateBuilder<TriggerInfo>();
            var symbol = context.TargetSymbol;
            if (symbol is IAssemblySymbol)
            {
                return results.ToImmutable();
            }

            var eventSymbol = symbol as IEventSymbol;
            if (eventSymbol == null && symbol is IFieldSymbol fieldSymbol)
            {
                if (fieldSymbol.ContainingType != null)
                {
                    eventSymbol = FindEvent(fieldSymbol.ContainingType, fieldSymbol.Name);
                }
            }

            if (eventSymbol != null)
            {
                var diagnosticLocation = context.TargetNode?.GetLocation() ?? Location.None;
                results.Add(CreateTriggerInfo(eventSymbol, diagnosticLocation, includeTypeNamePrefix: false, compilation: context.SemanticModel.Compilation));
            }

            return results.ToImmutable();
        }

        private ImmutableArray<TriggerInfo> GetAssemblyTriggers(Compilation compilation)
        {
            var results = ImmutableArray.CreateBuilder<TriggerInfo>();

            foreach (var attributeData in compilation.Assembly.GetAttributes())
            {
                if (!IsAttribute(attributeData, GenerateTypedTriggerAttributeName)) continue;
                if (attributeData.ConstructorArguments.Length != 2) continue;

                var targetType = attributeData.ConstructorArguments[0].Value as INamedTypeSymbol;
                var eventName = attributeData.ConstructorArguments[1].Value as string;

                if (targetType == null || string.IsNullOrEmpty(eventName))
                {
                    results.Add(new TriggerInfo("", "", "public", "", "", "", ImmutableArray<TriggerParameter>.Empty, Diagnostic.Create(TriggerEventNotFoundDiagnostic, Location.None, eventName ?? "<unknown>", targetType?.Name ?? "<unknown>")));
                    continue;
                }

                results.AddRange(CreateTriggerInfos(targetType, eventName!, Location.None, compilation));
            }

            return results.ToImmutable();
        }

        private void ExecuteGenerateTrigger(SourceProductionContext spc, TriggerInfo info)
        {
            if (info.Diagnostic != null)
            {
                spc.ReportDiagnostic(info.Diagnostic);
                return;
            }

            var sourceTypeName = TrimNullableAnnotation(info.TargetTypeName);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Avalonia;");
            sb.AppendLine("using Avalonia.Xaml.Interactivity;");
            sb.AppendLine("using Avalonia.Controls;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }
            sb.AppendLine($"    {info.Accessibility} partial class {info.ClassName} : Avalonia.Xaml.Interactivity.StyledElementTrigger");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly StyledProperty<object?> SourceObjectProperty =");
            sb.AppendLine($"            AvaloniaProperty.Register<{info.ClassName}, object?>(nameof(SourceObject));");
            sb.AppendLine();
            sb.AppendLine("        public object? SourceObject");
            sb.AppendLine("        {");
            sb.AppendLine("            get => GetValue(SourceObjectProperty);");
            sb.AppendLine("            set => SetValue(SourceObjectProperty, value);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private EventProxy? _proxy;");
            sb.AppendLine($"        private object? _resolvedSource;");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnAttached()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnAttached();");
            sb.AppendLine("            UpdateSource();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnDetaching()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnDetaching();");
            sb.AppendLine("            if (_resolvedSource is not null)");
            sb.AppendLine("            {");
            sb.AppendLine("                 UnregisterEvent(_resolvedSource);");
            sb.AppendLine("                 _resolvedSource = null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnPropertyChanged(change);");
            sb.AppendLine("            if (change.Property == SourceObjectProperty)");
            sb.AppendLine("            {");
            sb.AppendLine("                UpdateSource();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void UpdateSource()");
            sb.AppendLine("        {");
            sb.AppendLine("            var newSource = SourceObject ?? AssociatedObject;");
            sb.AppendLine("            if (newSource != _resolvedSource)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (_resolvedSource is not null) UnregisterEvent(_resolvedSource);");
            sb.AppendLine("                _resolvedSource = newSource;");
            sb.AppendLine("                if (_resolvedSource is not null) RegisterEvent(_resolvedSource);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void RegisterEvent(object source)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (source is {info.TargetTypeName} typedSource)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _proxy = new EventProxy(this, typedSource);");
            sb.AppendLine($"                typedSource.{info.EventName} += _proxy.OnEvent;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void UnregisterEvent(object source)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (source is {info.TargetTypeName} typedSource && _proxy != null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                typedSource.{info.EventName} -= _proxy.OnEvent;");
            sb.AppendLine($"                _proxy = null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            var parameters = FormatParameters(info.Parameters);
            var args = FormatArguments(info.Parameters);
            var eventArgsArgument = info.Parameters.Length == 0 ? "null" : info.Parameters.Last().Name;
            sb.AppendLine($"        private void OnEvent({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            Interaction.ExecuteActions(AssociatedObject, this.Actions, {eventArgsArgument});");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class EventProxy");
            sb.AppendLine("        {");
            sb.AppendLine($"            private readonly WeakReference<{info.ClassName}> _trigger;");
            sb.AppendLine($"            private readonly WeakReference<{sourceTypeName}> _source;");
            sb.AppendLine();
            sb.AppendLine($"            public EventProxy({info.ClassName} trigger, {sourceTypeName} source)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _trigger = new WeakReference<{info.ClassName}>(trigger);");
            sb.AppendLine($"                _source = new WeakReference<{sourceTypeName}>(source);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            public void OnEvent({parameters})");
            sb.AppendLine("            {");
            sb.AppendLine("                if (_trigger.TryGetTarget(out var trigger))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    trigger.OnEvent({args});");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (_source.TryGetTarget(out var typedSource))");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        typedSource.{info.EventName} -= OnEvent;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine("}");
            }

            spc.AddSource(CreateHintName(info.Namespace, info.ClassName), SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static Diagnostic? ValidateEventSymbol(IEventSymbol eventSymbol, Location? diagnosticLocation, Compilation? compilation)
        {
            var location = diagnosticLocation ?? Location.None;

            if (eventSymbol.IsStatic)
            {
                return Diagnostic.Create(StaticMemberNotSupportedDiagnostic, location, eventSymbol.Name);
            }

            var containingTypeDiagnostic = ValidateTypeAccessibility(eventSymbol.ContainingType, location, compilation);
            if (containingTypeDiagnostic != null)
            {
                return containingTypeDiagnostic;
            }

            var accessSymbol = (ISymbol?)eventSymbol.AddMethod ?? eventSymbol;
            if (!IsAccessibleToGenerator(accessSymbol, compilation))
            {
                return Diagnostic.Create(MemberNotAccessibleDiagnostic, location, eventSymbol.Name, eventSymbol.ContainingType.ToDisplayString());
            }

            if (ContainsTypeParameter(eventSymbol.ContainingType) || ContainsTypeParameter(eventSymbol.Type))
            {
                return Diagnostic.Create(GenericMemberNotSupportedDiagnostic, location, eventSymbol.Name);
            }

            return null;
        }

        private ImmutableArray<TriggerInfo> GetAssemblyTriggerFromAttributeSyntax(GeneratorSyntaxContext context)
        {
            if (context.Node is not AttributeSyntax attributeSyntax)
                return ImmutableArray<TriggerInfo>.Empty;

            var attributeType = context.SemanticModel.GetTypeInfo(attributeSyntax).Type;
            if (!IsAttributeType(attributeType, GenerateTypedTriggerAttributeName))
                return ImmutableArray<TriggerInfo>.Empty;

            if (attributeSyntax.ArgumentList?.Arguments.Count != 2)
                return ImmutableArray<TriggerInfo>.Empty;

            if (attributeSyntax.ArgumentList.Arguments[0].Expression is not TypeOfExpressionSyntax typeOfExpression)
                return ImmutableArray<TriggerInfo>.Empty;

            if (attributeSyntax.ArgumentList.Arguments[1].Expression is not LiteralExpressionSyntax eventLiteral)
                return ImmutableArray<TriggerInfo>.Empty;

            var eventName = eventLiteral.Token.ValueText;
            var targetType = context.SemanticModel.GetTypeInfo(typeOfExpression.Type).Type as INamedTypeSymbol;
            if (targetType == null || string.IsNullOrEmpty(eventName))
                return ImmutableArray<TriggerInfo>.Empty;

            return CreateTriggerInfos(targetType, eventName, context.Node.GetLocation(), context.SemanticModel.Compilation);
        }

        private ImmutableArray<TriggerInfo> CreateTriggerInfos(INamedTypeSymbol targetType, string eventPattern, Location? diagnosticLocation = null, Compilation? compilation = null)
        {
            var matchingEvents = FindMatchingEvents(targetType, eventPattern);
            if (matchingEvents.Length == 0)
            {
                var diagnostic = Diagnostic.Create(TriggerEventNotFoundDiagnostic, diagnosticLocation ?? Location.None, eventPattern, targetType.Name);
                return ImmutableArray.Create(new TriggerInfo("", "", "public", eventPattern, "", "", ImmutableArray<TriggerParameter>.Empty, diagnostic));
            }

            var builder = ImmutableArray.CreateBuilder<TriggerInfo>();
            var invalidBuilder = ImmutableArray.CreateBuilder<TriggerInfo>();
            foreach (var evt in matchingEvents)
            {
                var info = CreateTriggerInfo(evt, diagnosticLocation, includeTypeNamePrefix: true, compilation: compilation);
                if (info.Diagnostic is null)
                {
                    builder.Add(info);
                }
                else
                {
                    invalidBuilder.Add(info);
                }
            }

            if (builder.Count > 0)
            {
                return builder.ToImmutable();
            }

            if (invalidBuilder.Count > 0)
            {
                return invalidBuilder.ToImmutable();
            }

            var fallback = Diagnostic.Create(TriggerEventNotFoundDiagnostic, diagnosticLocation ?? Location.None, eventPattern, targetType.Name);
            return ImmutableArray.Create(new TriggerInfo("", "", "public", eventPattern, "", "", ImmutableArray<TriggerParameter>.Empty, fallback));
        }

        private TriggerInfo CreateTriggerInfo(IEventSymbol eventSymbol, Location? diagnosticLocation = null, bool includeTypeNamePrefix = false, Compilation? compilation = null)
        {
            var targetType = eventSymbol.ContainingType;
            var ns = targetType?.ContainingNamespace.ToDisplayString();
            var namespaceName = (targetType?.ContainingNamespace.IsGlobalNamespace == true || ns == "<global namespace>") ? null : ns;
            var baseName = $"{eventSymbol.Name}Trigger";
            var typePrefix = includeTypeNamePrefix && targetType != null ? GetTypeNamePrefix(targetType) : string.Empty;
            var className = string.IsNullOrEmpty(typePrefix) ? baseName : typePrefix + baseName;
            var targetTypeName = targetType != null ? ToDisplayStringWithNullable(targetType) : string.Empty;
            var eventName = eventSymbol.Name;
            var eventHandlerType = ToDisplayStringWithNullable(eventSymbol.Type);
            var requiresInternal = targetType?.DeclaredAccessibility == Accessibility.Internal ||
                                   eventSymbol.DeclaredAccessibility == Accessibility.Internal ||
                                   ContainsInternalType(eventSymbol.Type);
            var validationDiagnostic = ValidateEventSymbol(eventSymbol, diagnosticLocation, compilation);
            if (validationDiagnostic != null)
            {
                var accessibility = requiresInternal ? "internal" : "public";
                return new TriggerInfo(namespaceName, className, accessibility, targetTypeName, eventName, eventHandlerType, ImmutableArray<TriggerParameter>.Empty, validationDiagnostic);
            }

            var invokeMethod = (eventSymbol.Type as INamedTypeSymbol)?.DelegateInvokeMethod;
            if (invokeMethod == null)
            {
                var accessibility = requiresInternal ? "internal" : "public";
                return new TriggerInfo(namespaceName, className, accessibility, targetTypeName, eventName, eventHandlerType, ImmutableArray<TriggerParameter>.Empty, Diagnostic.Create(TriggerUnsupportedDelegateDiagnostic, diagnosticLocation ?? Location.None, eventName, eventHandlerType));
            }

            if (!invokeMethod.ReturnsVoid)
            {
                var accessibility = requiresInternal ? "internal" : "public";
                return new TriggerInfo(namespaceName, className, accessibility, targetTypeName, eventName, eventHandlerType, ImmutableArray<TriggerParameter>.Empty, Diagnostic.Create(TriggerUnsupportedDelegateReturnTypeDiagnostic, diagnosticLocation ?? Location.None, eventName, eventHandlerType));
            }

            var parameters = invokeMethod.Parameters.Select(p =>
            {
                var name = EscapeIdentifier(p.Name);
                var typeName = ToDisplayStringWithNullable(p.Type);
                return new TriggerParameter(name, typeName, p.RefKind);
            }).ToImmutableArray();
            if (invokeMethod.Parameters.Any(p => ContainsInternalType(p.Type)))
            {
                requiresInternal = true;
            }

            if (parameters.Any(p => p.RefKind == RefKind.Out))
            {
                var accessibility = requiresInternal ? "internal" : "public";
                return new TriggerInfo(namespaceName, className, accessibility, targetTypeName, eventName, eventHandlerType, parameters, Diagnostic.Create(TriggerUnsupportedDelegateOutParameterDiagnostic, diagnosticLocation ?? Location.None, eventName, eventHandlerType));
            }

            var finalAccessibility = requiresInternal ? "internal" : "public";
            return new TriggerInfo(namespaceName, className, finalAccessibility, targetTypeName, eventName, eventHandlerType, parameters);
        }

        private static IEnumerable<TriggerInfo> EnsureUniqueTriggers(IEnumerable<TriggerInfo> infos)
        {
            foreach (var group in infos.GroupBy(info => (info.Namespace, info.ClassName)))
            {
                var distinct = group
                    .GroupBy(info => (info.TargetTypeName, info.EventName))
                    .Select(g => g.FirstOrDefault(info => info.Diagnostic is null) ?? g.First())
                    .ToList();

                if (distinct.Count == 1)
                {
                    yield return distinct[0];
                    continue;
                }

                foreach (var info in distinct)
                {
                    yield return info with { ClassName = MakeUniqueName(info.ClassName, info.TargetTypeName) };
                }
            }
        }
    }
}
