// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Xaml.Behaviors.SourceGenerators
{
    public partial class XamlBehaviorsGenerator
    {
        private record ChangePropertyInfo(
            string? Namespace,
            string ClassName,
            string TargetTypeName,
            string PropertyName,
            string PropertyType,
            Diagnostic? Diagnostic = null);

        private void RegisterChangePropertyActionGeneration(IncrementalGeneratorInitializationContext context)
        {
            var propertyActions = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateTypedChangePropertyActionAttributeName,
                    predicate: static (_, _) => true,
                    transform: (ctx, _) => GetChangePropertyActionToGenerate(ctx))
                .SelectMany((x, _) => x);

            var assemblyPropertyActions = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsAssemblyAttribute(node, "GenerateTypedChangePropertyAction"),
                    transform: (ctx, _) => GetAssemblyChangePropertyFromAttributeSyntax(ctx))
                .Where(info => info is not null)
                .Select((info, _) => info!);

            var uniquePropertyActions = propertyActions
                .Collect()
                .Combine(assemblyPropertyActions.Collect())
                .SelectMany((data, _) => EnsureUniqueChangePropertyActions(data.Left.Concat(data.Right)));

            context.RegisterSourceOutput(uniquePropertyActions, ExecuteGenerateChangePropertyAction);
        }

        private ImmutableArray<ChangePropertyInfo> GetChangePropertyActionToGenerate(GeneratorAttributeSyntaxContext context)
        {
            var results = ImmutableArray.CreateBuilder<ChangePropertyInfo>();
            var symbol = context.TargetSymbol;
            if (symbol is IAssemblySymbol)
            {
                return results.ToImmutable();
            }

            if (symbol is IPropertySymbol propertySymbol)
            {
                var targetType = propertySymbol.ContainingType;
                if (targetType != null)
                {
                    var diagnosticLocation = context.TargetNode?.GetLocation() ?? Location.None;
                    var validationDiagnostic = ValidatePropertySymbol(propertySymbol, diagnosticLocation);
                    if (validationDiagnostic != null)
                    {
                        results.Add(new ChangePropertyInfo("", "", "", propertySymbol.Name, "", validationDiagnostic));
                        return results.ToImmutable();
                    }

                    var ns = targetType.ContainingNamespace.ToDisplayString();
                    var namespaceName = (targetType.ContainingNamespace.IsGlobalNamespace || ns == "<global namespace>") ? null : ns;
                    var className = $"Set{propertySymbol.Name}Action";
                    var targetTypeName = ToDisplayStringWithNullable(targetType);
                    var propertyName = propertySymbol.Name;
                    var propertyType = ToDisplayStringWithNullable(propertySymbol.Type);

                    results.Add(new ChangePropertyInfo(namespaceName, className, targetTypeName, propertyName, propertyType));
                }
            }
            return results.ToImmutable();
        }

        private void ExecuteGenerateChangePropertyAction(SourceProductionContext spc, ChangePropertyInfo info)
        {
            if (info.Diagnostic != null)
            {
                spc.ReportDiagnostic(info.Diagnostic);
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Avalonia;");
            sb.AppendLine("using Avalonia.Xaml.Interactivity;");
            sb.AppendLine("using Avalonia.Controls;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }
            sb.AppendLine($"    public partial class {info.ClassName} : Avalonia.Xaml.Interactivity.StyledElementAction");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly StyledProperty<object?> TargetObjectProperty =");
            sb.AppendLine($"            AvaloniaProperty.Register<{info.ClassName}, object?>(nameof(TargetObject));");
            sb.AppendLine();
            sb.AppendLine($"        public static readonly StyledProperty<{info.PropertyType}> ValueProperty =");
            sb.AppendLine($"            AvaloniaProperty.Register<{info.ClassName}, {info.PropertyType}>(nameof(Value));");
            sb.AppendLine();
            sb.AppendLine("        public object? TargetObject");
            sb.AppendLine("        {");
            sb.AppendLine("            get => GetValue(TargetObjectProperty);");
            sb.AppendLine("            set => SetValue(TargetObjectProperty, value);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {info.PropertyType} Value");
            sb.AppendLine("        {");
            sb.AppendLine("            get => GetValue(ValueProperty);");
            sb.AppendLine("            set => SetValue(ValueProperty, value);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override object Execute(object? sender, object? parameter)");
            sb.AppendLine("        {");
            sb.AppendLine("            var target = TargetObject ?? sender;");
            sb.AppendLine($"            if (target is {info.TargetTypeName} typedTarget)");
            sb.AppendLine("            {");
            sb.AppendLine($"                typedTarget.{info.PropertyName} = Value;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource(CreateHintName(info.Namespace, info.ClassName), SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static Diagnostic? ValidatePropertySymbol(IPropertySymbol propertySymbol, Location? diagnosticLocation)
        {
            var location = diagnosticLocation ?? Location.None;

            if (propertySymbol.IsStatic)
            {
                return Diagnostic.Create(StaticMemberNotSupportedDiagnostic, location, propertySymbol.Name);
            }

            var containingTypeDiagnostic = ValidateTypeAccessibility(propertySymbol.ContainingType, location);
            if (containingTypeDiagnostic != null)
            {
                return containingTypeDiagnostic;
            }

            if (!HasAccessibleSetter(propertySymbol))
            {
                return Diagnostic.Create(PropertySetterNotAccessibleDiagnostic, location, propertySymbol.Name, propertySymbol.ContainingType.ToDisplayString());
            }

            if (propertySymbol.SetMethod?.IsInitOnly == true)
            {
                return Diagnostic.Create(InitOnlySetterNotSupportedDiagnostic, location, propertySymbol.Name, propertySymbol.ContainingType.ToDisplayString());
            }

            if (ContainsTypeParameter(propertySymbol.ContainingType) || ContainsTypeParameter(propertySymbol.Type))
            {
                return Diagnostic.Create(GenericMemberNotSupportedDiagnostic, location, propertySymbol.Name);
            }

            return null;
        }

        private ChangePropertyInfo? GetAssemblyChangePropertyFromAttributeSyntax(GeneratorSyntaxContext context)
        {
            if (context.Node is not AttributeSyntax attributeSyntax)
                return null;

            if (attributeSyntax.ArgumentList?.Arguments.Count != 2)
                return null;

            if (attributeSyntax.ArgumentList.Arguments[0].Expression is not TypeOfExpressionSyntax typeOfExpression)
                return null;

            if (attributeSyntax.ArgumentList.Arguments[1].Expression is not LiteralExpressionSyntax propertyLiteral)
                return null;

            var propertyName = propertyLiteral.Token.ValueText;
            var targetType = context.SemanticModel.GetTypeInfo(typeOfExpression.Type).Type as INamedTypeSymbol;
            if (targetType == null || string.IsNullOrEmpty(propertyName))
            {
                var diagnostic = Diagnostic.Create(ChangePropertyNotFoundDiagnostic, Location.None, propertyName ?? "<unknown>", targetType?.Name ?? "<unknown>");
                return new ChangePropertyInfo("", "", "", propertyName ?? "<unknown>", "", diagnostic);
            }

            var info = CreateChangePropertyInfo(targetType, propertyName, context.Node.GetLocation());
            return info;
        }

        private ImmutableArray<ChangePropertyInfo> GetAssemblyChangePropertyActions(Compilation compilation)
        {
            var results = ImmutableArray.CreateBuilder<ChangePropertyInfo>();

            foreach (var attributeData in compilation.Assembly.GetAttributes())
            {
                if (!IsAttribute(attributeData, GenerateTypedChangePropertyActionAttributeName)) continue;
                if (attributeData.ConstructorArguments.Length != 2) continue;

                var targetType = attributeData.ConstructorArguments[0].Value as INamedTypeSymbol;
                var propertyName = attributeData.ConstructorArguments[1].Value as string;

                if (targetType == null || string.IsNullOrEmpty(propertyName))
                {
                    var diagnostic = Diagnostic.Create(ChangePropertyNotFoundDiagnostic, Location.None, propertyName ?? "<unknown>", targetType?.Name ?? "<unknown>");
                    results.Add(new ChangePropertyInfo("", "", "", "", "", diagnostic));
                    continue;
                }

                results.Add(CreateChangePropertyInfo(targetType, propertyName!, Location.None));
            }

            return results.ToImmutable();
        }

        private ChangePropertyInfo CreateChangePropertyInfo(INamedTypeSymbol targetType, string propertyName, Location? diagnosticLocation = null)
        {
            var propertySymbol = FindProperty(targetType, propertyName);
            if (propertySymbol != null)
            {
                var validationDiagnostic = ValidatePropertySymbol(propertySymbol, diagnosticLocation);
                if (validationDiagnostic != null)
                {
                    return new ChangePropertyInfo("", "", "", propertyName, "", validationDiagnostic);
                }
            }

            var propertyTypeSymbol = propertySymbol?.Type ?? FindPropertyType(targetType, propertyName);
            if (propertyTypeSymbol == null)
            {
                var diagnostic = Diagnostic.Create(ChangePropertyNotFoundDiagnostic, Location.None, propertyName, targetType.Name);
                return new ChangePropertyInfo("", "", "", propertyName, "", diagnostic);
            }

            var propertyType = ToDisplayStringWithNullable(propertyTypeSymbol);

            var ns = targetType.ContainingNamespace.ToDisplayString();
            var namespaceName = (targetType.ContainingNamespace.IsGlobalNamespace || ns == "<global namespace>") ? null : ns;
            var className = $"Set{propertyName}Action";
            var targetTypeName = ToDisplayStringWithNullable(targetType);

            return new ChangePropertyInfo(namespaceName, className, targetTypeName, propertyName, propertyType);
        }

        private static IEnumerable<ChangePropertyInfo> EnsureUniqueChangePropertyActions(IEnumerable<ChangePropertyInfo> infos)
        {
            foreach (var group in infos.GroupBy(info => (info.Namespace, info.ClassName)))
            {
                var distinct = group
                    .GroupBy(info => (info.TargetTypeName, info.PropertyName))
                    .Select(g => g.FirstOrDefault(info => info.Diagnostic is null) ?? g.First())
                    .ToList();

                if (distinct.Count == 1)
                {
                    yield return distinct[0];
                    continue;
                }

                foreach (var info in distinct)
                {
                    yield return info with { ClassName = MakeUniqueName(info.ClassName, info.TargetTypeName) };
                }
            }
        }
    }
}
