<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>False</IsPackable>
    <Nullable>enable</Nullable>
    <UnoRuntimeIdentifier>Skia</UnoRuntimeIdentifier>
    <AssemblyName>Xaml.Behaviors.Uno.Interactivity.UnitTests</AssemblyName>
    <RootNamespace>Xaml.Interactivity.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" VersionOverride="$(UnoWinUIVersion)" />
    <PackageReference Include="Uno.WinUI.Runtime.Skia" />
  </ItemGroup>

  <Import Project="..\..\..\build\XUnit.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Uno\Xaml.Behaviors.Uno.Headless.Host\Xaml.Behaviors.Uno.Headless.Host.csproj" />
  </ItemGroup>

</Project>
